config/routes.rb
Rails.application.routes.draw do
  
  

  root 'bubbles#index'

  get 'sessions/create'

  get 'sessions/new'

  get 'sessions/destroy'

  get 'bubbles/upvote' => 'bubbles#upvote', as: :upvote
  get 'bubbles/downvote' => 'bubbles#downvote', as: :downvote

  get 'comments/upvotecomment' => 'comments#upvotecomment', as: :upvotecomment
  get 'comments/downvotecomment' => 'comments#downvotecomment', as: :downvotecomment

  resources :bubbles do
    member do
    end

  resources :comments
  end

  resources :users, except: [:destroy]
  resource :sessions, only: [:create, :new, :destroy]

  get 'tag_search/index' => 'tag_search#index', as: :tag_search

  get 'tag_search/find' => 'tag_search#find', as: :find

  

  

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActionView::Helpers::DateHelper
  field :bubble_id, type: Integer
  field :body, type: String
  field :vote_count, type: Integer, default: 0
  field :score, type: Integer, default: 0

  
  belongs_to :user
  belongs_to :bubble


  def comment_score
  	score = self.vote_count
  	self.update_attribute(:score, score)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :upvotecomment, :downvotecomment, :index]


def index
    @comment = Comment.desc(:score)
end



def upvotecomment
    @comment = Comment.find(params[:id])
    @comment.vote_count += 1
    if @comment.save
      @comment.comment_score
      redirect_to :back
    end
  end

  def downvotecomment
    @comment = Comment.find(params[:id])
    @comment.vote_count -= 1
    if @comment.save
      @comment.comment_score
      redirect_to :back
    end
  end



  def create
    @bubble = Bubble.find(params[:bubble_id])
    @comment = @bubble.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @bubble }
        format.json { render :show, status: :created, location: @comment }
        @bubble.bubble_score


      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end







  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:bubble_id, :body, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do |f| %>
   <div class="voting_container_show">

  <div class="arrow"><%= link_to content_tag(:i,nil, :class=>"fa fa-chevron-up"), upvotecomment_path(:id => comment.id) %></div>

  <div class="votes"><%= comment.vote_count %></div>

  <div class="arrow"><%= link_to link_to content_tag(:i,nil, :class=>"fa fa-chevron-down"), downvotecomment_path(:id => comment.id) %></div>
</div>  

<div class="comments"><%= comment.body %></div>

  


 


<div class="meta_data_row_show" id="comment_left_indent">
	<% if current_user == @bubble.user %>
          Commented by <%= link_to 'you', current_user %> | <%= comment.time_ago_in_words(comment.created_at) %> ago
  <% else %>
  Commented by <%= link_to @bubble.user.name, @bubble.user %> | <%= comment.time_ago_in_words(comment.created_at) %> ago


  <% end %> 

  | <%= comment.score %>

 </div> 
  <div class="dashed_line"></div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>


  <div class="field">
    <%= f.label :bubble_id %><br>
    <%= f.number_field :bubble_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :placeholder => "Add your comment here"  %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Bubble Id</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.bubble_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bubble Id:</strong>
  <%= @comment.bubble_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>