config/routes.rb
Rails.application.routes.draw do
  
  

  root 'bubbles#index'

  get 'sessions/create'

  get 'sessions/new'

  get 'sessions/destroy'

  get 'bubbles/upvote' => 'bubbles#upvote', as: :upvote
  get 'bubbles/downvote' => 'bubbles#downvote', as: :downvote

  get 'comments/upvotecomment' => 'comments#upvotecomment', as: :upvotecomment
  get 'comments/downvotecomment' => 'comments#downvotecomment', as: :downvotecomment

  resources :bubbles do
    member do
    end

  resources :comments
  end

  resources :users, except: [:destroy]
  resource :sessions, only: [:create, :new, :destroy]

  get 'tag_search/index' => 'tag_search#index', as: :tag_search

  get 'tag_search/find' => 'tag_search#find', as: :find

  

  

end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  has_secure_password
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  has_many :bubbles
  has_many :comments


  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
         format.html { 
          session[:user_id] = @user.id.to_s
          redirect_to bubbles_path, notice: 'User was successfully created.'
        }
        format.json { render action: 'show', status: :created, location: @user }

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="left_indent_container">
  <div class="field">
    <%= f.text_field :name, :class => "login_field", :placeholder => "Name"   %>
  </div>
  <div class="field">
    <%= f.text_field :email, :class => "login_field", :placeholder => "Email address"   %>
  </div>
  <div class="field">
    <%= f.password_field :password, :class => "login_field", :placeholder => "Password"  %>
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation, :class => "login_field", :placeholder => "Password confirmation"  %>
  </div>
  <div class="actions">
    <%= f.submit "Save", :class => "login_button"%>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<div class="page_header">Update your account</div>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="page_header">Sign up</div>

<%= render 'form' %>

app/views/users/show.html.erb
  <div class="page_header">Posts by <%= @user.name %> </div>



<div class="bubbles_container">

 <% @user.bubbles.sort_by!(&:created_at).reverse.each do |bubble|%>
  <% bubble.time_bonus %><% bubble.bubble_score %>


  <div class="dashed_line"></div>

  <table class="bubble_table">
    <td class_"voting_table_cell">
      <div class="voting_container">
          <div class="arrow"><%= link_to content_tag(:i,nil, :class=>"fa fa-chevron-up"), upvote_path(:id => bubble.id) %></div>


          <div class="votes"><%= bubble.vote_count %></div>
     

 
          <div class="arrow"><%= link_to content_tag(:i,nil, :class=>"fa fa-chevron-down"), downvote_path(:id => bubble.id) %></div>

      </div>
    </td>
    <td>
      <span class="score_stuff"><% if current_user == bubble.user %> 
	        <span class="meta_link"><%= link_to 'Edit', edit_bubble_path(bubble) %></span>
	        <span class="meta_link"><%= link_to 'Delete', bubble, method: :delete, data: { confirm: 'Are you sure?' } %></span>
	        <% end %><%= bubble.score %> | <%= bubble.time_bonus_value %></span>

      <div class="bubble_object_container">
        <div class="bubble_title"><%= link_to bubble.title, bubble %></div>
        


        <div class="meta_data_row">
          <span class="tag_link"><%= link_to bubble.tag, find_path(:tag => bubble.tag) %>  </span>

          
           <span class="meta_link"><%= link_to bubble.user.name, bubble.user %></span>
          

          <%= bubble.time_ago_in_words(bubble.created_at) %> ago

          <span class="meta_link"><%= link_to bubble.comments.count, bubble %><%= link_to ' Comments', bubble %>
    		</span>   

    	
	               
          
          

        </div>

      </div
    </td>

    </table>

  <% end %>