config/routes.rb
Rails.application.routes.draw do
  
  

  root 'bubbles#index'

  get 'sessions/create'

  get 'sessions/new'

  get 'sessions/destroy'

  get 'bubbles/upvote' => 'bubbles#upvote', as: :upvote
  get 'bubbles/downvote' => 'bubbles#downvote', as: :downvote

  get 'comments/upvotecomment' => 'comments#upvotecomment', as: :upvotecomment
  get 'comments/downvotecomment' => 'comments#downvotecomment', as: :downvotecomment

  resources :bubbles do
    member do
    end

  resources :comments
  end

  resources :users, except: [:destroy]
  resource :sessions, only: [:create, :new, :destroy]

  get 'tag_search/index' => 'tag_search#index', as: :tag_search

  get 'tag_search/find' => 'tag_search#find', as: :find

  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClassIndex</title>
 
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='https://fonts.googleapis.com/css?family=Bitter:400,700,400italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Lekton' rel='stylesheet' type='text/css'>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 
 true %>
 <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
 <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

<div class="big_gear"><%= link_to 'C', bubbles_path %></div>
	


		<div class="user_header_items">
			<% if current_user %>
				<span class="user_header_link"> <%= link_to "My posts", current_user %></span>
				<span class="user_header_link"><%= link_to "Account", edit_user_path(current_user) %></span>
				<span class="user_header_link"><%= link_to "Logout", sessions_path, method: :delete %></span>

			<% else %>
				<span class="user_header_link"><%= link_to "Login", new_sessions_path%></span> 
				<span class="user_header_link"><%= link_to "Sign up", new_user_path %></span>
				<br>
			<% end %>
		</div>

	<%= yield %>

</body>
</html>